dist: trusty
sudo: false

addons:
  apt:
    packages:
      - pkg-config
      - libglib2.0-dev
      - libcairo2-dev
      - libtiff4-dev
      - libexif-dev
      - libgif-dev
      - libjpeg-dev
      - libunwind8

before_install:
  - wget -nv -nc https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-dev-ubuntu-x64.latest.tar.gz -O dotnet-dev-ubuntu-x64.latest.tar.gz
  - mkdir dotnet
  - tar -C dotnet -k -xvzf dotnet-dev-ubuntu-x64.latest.tar.gz

install:
  - ./clone-mono.sh
  - ./clone-gdiplus.sh

script:
  - cd libgdiplus
  - ./autogen.sh
  - make
  - cd ..
  - dotnet/dotnet restore System.Drawing.sln
  - dotnet/dotnet build System.Drawing.sln
  - MALLOC_CHECK_=1 LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/libgdiplus/src/.libs/ dotnet/dotnet run -p test/CoreCompat.System.Drawing.Tests/CoreCompat.System.Drawing.Tests.csproj --where "cat != NotWorking && Method != ToLogFont_AssertUnmanagedCode && Method != ToLogFont_DenyUnmanagedCode && Method != FromHwnd_Zero"
